### ISSUE TITLE
Build failure with GHC 9.8

### ISSUE THREAD

**Issue by andreasabel** [glguy/th-abstraction#105]
Some types apparently have changed in `template-haskell`, there is now a mismatch between `TyVarBndrUnit` and `TyVarBndr BndrVis`.
```
src/Language/Haskell/TH/Datatype.hs:598:38: error: [GHC-83865]
    • Couldn't match type ‘BndrVis’ with ‘()’
      Expected: [TyVarBndrUnit]
        Actual: [TyVarBndr BndrVis]
    • In the first argument of ‘repairVarKindsWith’, namely ‘dvars’
      In a stmt of a 'do' block: ts' <- repairVarKindsWith dvars dk ts
      In the expression:
        do ts' <- repairVarKindsWith dvars dk ts
           return $ NewtypeInstD cx mbInstVars (foldl' AppT con ts') k c deriv
    |
598 |       = do ts' <- repairVarKindsWith dvars dk ts
    |                                      ^^^^^
...
```
Seems like the details behind this error have been reported in
- #103

A release on hackage compatible with the latest template-haskell / GHC would be nice.

**Comment by RyanGlScott** [comment]
I've prepared a fix for this issue (and #103, which is essentially the same issue) in #104, which is based on the corresponding `head.hackage` patch [here](https://gitlab.haskell.org/ghc/head.hackage/-/blob/43f961235ac97f4229e1ad5aaabf7bd70a8ef694/patches/th-abstraction-0.5.0.0.patch). I've held off on releasing it pending a resolution to https://github.com/ghc-proposals/ghc-proposals/pull/604 (which could impact how `TypeAbstractions` works in GHC 9.8), but upon a closer read, that proposal is unlikely to affect `th-abstraction` in particular.

I'll try to cut a new `th-abstraction` release soon.

**Comment by RyanGlScott** [comment]
I've uploaded [`th-abstraction-0.6.0.0`](https://hackage.haskell.org/package/th-abstraction-0.6.0.0) to Hackage, which contains the changes from #104. As such, I'll close this issue.

Do note that some downstream libraries that depend on `th-abstraction` will also need updates to support GHC 9.8. At a minimum, these include many of the libraries in [this `head.hackage` patch](https://gitlab.haskell.org/ghc/head.hackage/-/commit/88e98df254ba3643411337dc967abbbbd7c27853). I'll get around to updating those libraries which I maintain in the coming days.
