### ISSUE TITLE
Build on GHC 8.8 broken by its TH being 0.15.0 without AppKindT

### ISSUE THREAD

**Issue by deepfire** [glguy/th-abstraction#69]
https://github.com/glguy/th-abstraction/blob/94b36fdd250a04a2676826528c36d2fe35573b82/src/Language/Haskell/TH/Datatype.hs#L1380

```
[2 of 2] Compiling Language.Haskell.TH.Datatype ( src/Language/Haskell/TH/Datatype.hs, dist/bui

src/Language/Haskell/TH/Datatype.hs:1380:14: error:
    Not in scope: data constructor �<80><98>AppKindT�<80><99>
     |
1380 |     go args (AppKindT f x) = go (TyArg x:args) f
     |              ^^^^^^^^

src/Language/Haskell/TH/Datatype.hs:1466:18: error:
    Not in scope: data constructor �<80><98>AppKindT�<80><99>
     |
1466 | resolveInfixT (f `AppKindT` x)  = appKindT (resolveInfixT f) (resolveInfixT x)
     |                  ^^^^^^^^^^

src/Language/Haskell/TH/Datatype.hs:1629:18: error:
    Not in scope: data constructor �<80><98>AppKindT�<80><99>
     |
1629 |           go_ty (AppKindT t k) = go_ty t `mappend` go_ty k
     |                  ^^^^^^^^

src/Language/Haskell/TH/Datatype.hs:1742:11: error:
    Not in scope: data constructor �<80><98>AppKindT�<80><99>
     |
1742 |       go (AppKindT t k)  = AppKindT (go t) (go k)
     |           ^^^^^^^^

src/Language/Haskell/TH/Datatype.hs:1764:7: error:
    Not in scope: data constructor �<80><98>AppKindT�<80><99>
     |
1764 |       AppKindT t k  -> freeVariables t `union` freeVariables k
     |       ^^^^^^^^
```

**Comment by deepfire** [comment]
Relevant GHC code: http://git.haskell.org/ghc.git/blob/refs/heads/ghc-8.8:/libraries/template-haskell/Language/Haskell/TH/Syntax.hs#l2038

**Comment by RyanGlScott** [comment]
Is there a reason that you're not using the official upstream repo at https://gitlab.haskell.org/ghc/ghc/commits/ghc-8.8? (The link you've given is for an out-of-date mirror of that repo.)

**Comment by deepfire** [comment]
Excellent point, thank you Ryan.
