### ISSUE TITLE
Tests don't build with GHCJS 8.4

### ISSUE THREAD

**Issue by ElvishJerricco** [glguy/th-abstraction#53]
Full log: https://gist.github.com/ElvishJerricco/c3c649de21c10942b7439d0cc63dd5ff

I would not be surprised if this were a GHCJS bug. @luite, you might want to take a look.

**Comment by angerman** [comment]
I'm getting something very similar:
```
test/Main.hs:332:5: error:
    • The exact Name ‘MkT43Plain_ah7K’ is not in scope
        Probable cause: you used a unique Template Haskell name (NameU), 
        perhaps via newName, but did not bind it
        If that's it, then -ddump-splices might be useful
    • In the untyped splice:
        $(do [decPlain] <- [d| data T43Plain
                                 where MkT43Plain :: T43Plain |]
             infoPlain <- normalizeDec decPlain
             validateDI
               infoPlain
               DatatypeInfo
                 {datatypeName = mkName "T43Plain", datatypeContext = [],
                  datatypeVars = [], datatypeVariant = Datatype,
                  datatypeCons = [ConstructorInfo
                                    {constructorName = mkName "MkT43Plain", constructorVars = [],
                                     constructorContext = [], constructorFields = [],
                                     constructorStrictness = [],
                                     constructorVariant = NormalConstructor}]}
             [decFam] <- [d| data instance T43Fam where MkT43Fam :: T43Fam |]
             ....)
    |
332 |   $(do [decPlain] <- [d| data T43Plain where MkT43Plain :: T43Plain |]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

test/Main.hs:332:5: error:
    • The exact Name ‘MkT43Plain_ah7K’ is not in scope
        Probable cause: you used a unique Template Haskell name (NameU), 
        perhaps via newName, but did not bind it
        If that's it, then -ddump-splices might be useful
    • In the untyped splice:
        $(do [decPlain] <- [d| data T43Plain
                                 where MkT43Plain :: T43Plain |]
             infoPlain <- normalizeDec decPlain
             validateDI
               infoPlain
               DatatypeInfo
                 {datatypeName = mkName "T43Plain", datatypeContext = [],
                  datatypeVars = [], datatypeVariant = Datatype,
                  datatypeCons = [ConstructorInfo
                                    {constructorName = mkName "MkT43Plain", constructorVars = [],
                                     constructorContext = [], constructorFields = [],
                                     constructorStrictness = [],
                                     constructorVariant = NormalConstructor}]}
             [decFam] <- [d| data instance T43Fam where MkT43Fam :: T43Fam |]
             ....)
    |
332 |   $(do [decPlain] <- [d| data T43Plain where MkT43Plain :: T43Plain |]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

test/Main.hs:332:5: error:
    • The exact Name ‘MkT43Fam_ah7L’ is not in scope
        Probable cause: you used a unique Template Haskell name (NameU), 
        perhaps via newName, but did not bind it
        If that's it, then -ddump-splices might be useful
    • In the untyped splice:
        $(do [decPlain] <- [d| data T43Plain
                                 where MkT43Plain :: T43Plain |]
             infoPlain <- normalizeDec decPlain
             validateDI
               infoPlain
               DatatypeInfo
                 {datatypeName = mkName "T43Plain", datatypeContext = [],
                  datatypeVars = [], datatypeVariant = Datatype,
                  datatypeCons = [ConstructorInfo
                                    {constructorName = mkName "MkT43Plain", constructorVars = [],
                                     constructorContext = [], constructorFields = [],
                                     constructorStrictness = [],
                                     constructorVariant = NormalConstructor}]}
             [decFam] <- [d| data instance T43Fam where MkT43Fam :: T43Fam |]
             ....)
    |
332 |   $(do [decPlain] <- [d| data T43Plain where MkT43Plain :: T43Plain |]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

test/Main.hs:332:5: error:
    • The exact Name ‘MkT43Fam_ah7L’ is not in scope
        Probable cause: you used a unique Template Haskell name (NameU), 
        perhaps via newName, but did not bind it
        If that's it, then -ddump-splices might be useful
    • In the untyped splice:
        $(do [decPlain] <- [d| data T43Plain
                                 where MkT43Plain :: T43Plain |]
             infoPlain <- normalizeDec decPlain
             validateDI
               infoPlain
               DatatypeInfo
                 {datatypeName = mkName "T43Plain", datatypeContext = [],
                  datatypeVars = [], datatypeVariant = Datatype,
                  datatypeCons = [ConstructorInfo
                                    {constructorName = mkName "MkT43Plain", constructorVars = [],
                                     constructorContext = [], constructorFields = [],
                                     constructorStrictness = [],
                                     constructorVariant = NormalConstructor}]}
             [decFam] <- [d| data instance T43Fam where MkT43Fam :: T43Fam |]
             ....)
    |
332 |   $(do [decPlain] <- [d| data T43Plain where MkT43Plain :: T43Plain |]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
[iserv-proxy] Proxy done
builder for '/nix/store/m1kq4jy3lr0jg71c12ssrm0rla6663hf-th-abstraction-0.2.8.0-x86_64-pc-mingw32.drv' failed with exit code 1
```

This is *not* GHCJS though. This is using `ghc-8.4.3` + `-fexternal-interpreter`. That however is pretty close to how GHCJS does TH.

@RyanGlScott you might be able to reproduce this by simply building the package with `-fexternal-interpreter` passed to ghc.

**Comment by ElvishJerricco** [comment]
Should we close this issue now, seeing as this is a GHC issue, not a th-abstraction issue?

**Comment by RyanGlScott** [comment]
That sounds reasonable to me.
